name = "alsa"
description = "The Advanced Linux Sound Architecture (ALSA) library API binding."
version = "0.1.0"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]

project-files = ["gnat/alsa.gpr"]

configuration.output_dir = "gnat"
configuration.generate_ada = false
configuration.generate_c = false

[available.'case(os)']
'linux' = true
'...' = false
