name = "alsa_hello"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]

executables = ["alsa_hello"]
[[depends-on]]
alsa = "~0.1.0"
[[pins]]
alsa = { path='../..' }
